FEAT: Account Managment Screen
tinylunark/lunark-android pull request #5
Opened 2023-11-16 20:12 UTC by duolok

This PR adds a screen for Account Management. Users can change their profile info, update their password, and delete their account from here.
![demo_three](https://github.com/tinylunark/lunark-android/assets/42711489/e60ee400-1a9d-4736-ab7f-5a0040035b7b)
![demo_two](https://github.com/tinylunark/lunark-android/assets/42711489/616ef23d-199b-4acd-9abe-69c7e8b723dc)
![demo_one](https://github.com/tinylunark/lunark-android/assets/42711489/4b09b6c1-1d6b-4bf9-918d-43f738776d1c)

2023-11-17 15:13 UTC, vradovic requested changes

2023-11-17 15:13 UTC, vradovic commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
Remove this, it is already defined on line 9

2023-11-18 15:04 UTC, vradovic requested changes
The app launches from SplashScreen activity to the Account activity, it should probably launch to Home or Login activity instead :thinking: 

Also selecting Account from the navigation drawer doesn't open the Account screen

2023-11-18 15:14 UTC, duolok commented
> The app launches from SplashScreen activity to the Account activity, it should probably launch to Home or Login activity instead

Testing purposes.

> Also selecting Account from the navigation drawer doesn't open the Account screen

It will be updated in another PR.

2023-11-18 15:20 UTC, vradovic commented
Resolve conflicts as well please :pray:

2023-11-18 15:35 UTC, vradovic approved these changes

2023-11-18 15:37 UTC, merged